import type { GridProject, StationDoc, TopologyGraph } from './types'

function stationA(): StationDoc {
  const graph: TopologyGraph = {
    nodes: [
      {
        id: 'a_bus',
        type: 'bus',
        name: 'A-220kVⅠ母',
        stationId: 'stA',
        voltage: '220kV',
        x: 80,
        y: 100,
        width: 220,
        height: 10,
      },
      {
        id: 'a_ds_src',
        type: 'disconnector',
        name: 'A电源刀闸',
        stationId: 'stA',
        voltage: '220kV',
        closed: true,
        x: 120,
        y: 140,
      },
      {
        id: 'a_br_src',
        type: 'breaker',
        name: 'A电源开关',
        stationId: 'stA',
        voltage: '220kV',
        closed: true,
        x: 120,
        y: 190,
      },
      {
        id: 'a_power',
        type: 'powerSource',
        name: '系统电源',
        stationId: 'stA',
        voltage: '220kV',
        isPowerSource: true,
        x: 109,
        y: 250,
      },
      {
        id: 'a_ds_out1',
        type: 'disconnector',
        name: 'A出线刀闸1',
        stationId: 'stA',
        voltage: '220kV',
        closed: true,
        x: 230,
        y: 140,
      },
      {
        id: 'a_br_out',
        type: 'breaker',
        name: 'A出线开关',
        stationId: 'stA',
        voltage: '220kV',
        closed: true,
        x: 230,
        y: 190,
      },
      {
        id: 'a_boundary_ab',
        type: 'disconnector',
        name: 'A出线边界(至B)',
        stationId: 'stA',
        voltage: '220kV',
        closed: true,
        isBoundary: true,
        x: 230,
        y: 250,
      },
    ],
    edges: [
      { id: 'ae1', source: 'a_bus', target: 'a_ds_src' },
      { id: 'ae2', source: 'a_ds_src', target: 'a_br_src' },
      { id: 'ae3', source: 'a_br_src', target: 'a_power' },
      { id: 'ae4', source: 'a_bus', target: 'a_ds_out1' },
      { id: 'ae5', source: 'a_ds_out1', target: 'a_br_out' },
      { id: 'ae6', source: 'a_br_out', target: 'a_boundary_ab' },
    ],
  }
  return {
    id: 'stA',
    name: 'A变电站',
    voltageSummary: '220kV',
    busScheme: 'single',
    graph,
    ports: [
      {
        id: 'port_a_ab',
        stationId: 'stA',
        deviceId: 'a_boundary_ab',
        name: 'A出线边界(至B)',
      },
    ],
    overviewPosition: { x: 80, y: 160 },
  }
}

function stationB(): StationDoc {
  const graph: TopologyGraph = {
    nodes: [
      {
        id: 'b_boundary_ba',
        type: 'disconnector',
        name: 'B进线边界(自A)',
        stationId: 'stB',
        voltage: '220kV',
        closed: true,
        isBoundary: true,
        x: 100,
        y: 40,
      },
      {
        id: 'b_br_in',
        type: 'breaker',
        name: 'B进线开关',
        stationId: 'stB',
        voltage: '220kV',
        closed: true,
        x: 100,
        y: 90,
      },
      {
        id: 'b_ds_in',
        type: 'disconnector',
        name: 'B进线刀闸',
        stationId: 'stB',
        voltage: '220kV',
        closed: true,
        x: 100,
        y: 140,
      },
      {
        id: 'b_bus1',
        type: 'bus',
        name: 'B-220kVⅠ母',
        stationId: 'stB',
        voltage: '220kV',
        x: 60,
        y: 200,
        width: 200,
        height: 10,
      },
      {
        id: 'b_bus2',
        type: 'bus',
        name: 'B-220kVⅡ母',
        stationId: 'stB',
        voltage: '220kV',
        x: 60,
        y: 260,
        width: 200,
        height: 10,
      },
      {
        id: 'b_br_coupler',
        type: 'breaker',
        name: '母联开关',
        stationId: 'stB',
        voltage: '220kV',
        closed: true,
        x: 220,
        y: 220,
      },
      {
        id: 'b_ds_out',
        type: 'disconnector',
        name: 'B出线刀闸',
        stationId: 'stB',
        voltage: '220kV',
        closed: true,
        x: 300,
        y: 140,
      },
      {
        id: 'b_br_out',
        type: 'breaker',
        name: 'B出线开关',
        stationId: 'stB',
        voltage: '220kV',
        closed: true,
        x: 300,
        y: 90,
      },
      {
        id: 'b_boundary_bc',
        type: 'disconnector',
        name: 'B出线边界(至C)',
        stationId: 'stB',
        voltage: '220kV',
        closed: true,
        isBoundary: true,
        x: 300,
        y: 40,
      },
      {
        id: 'b_ds_xf',
        type: 'disconnector',
        name: '主变高压刀闸',
        stationId: 'stB',
        voltage: '220kV',
        closed: true,
        x: 140,
        y: 300,
      },
      {
        id: 'b_br_xf',
        type: 'breaker',
        name: '主变高压开关',
        stationId: 'stB',
        voltage: '220kV',
        closed: true,
        x: 140,
        y: 350,
      },
      {
        id: 'b_xf',
        type: 'transformer',
        name: '#1主变',
        stationId: 'stB',
        voltage: '220/110',
        x: 129,
        y: 405,
      },
      {
        id: 'b_bus_lv',
        type: 'bus',
        name: 'B-110kVⅠ母',
        stationId: 'stB',
        voltage: '110kV',
        x: 80,
        y: 490,
        width: 180,
        height: 10,
      },
      {
        id: 'b_load',
        type: 'load',
        name: 'B站负荷',
        stationId: 'stB',
        voltage: '110kV',
        x: 140,
        y: 530,
      },
    ],
    edges: [
      { id: 'be1', source: 'b_boundary_ba', target: 'b_br_in' },
      { id: 'be2', source: 'b_br_in', target: 'b_ds_in' },
      { id: 'be3', source: 'b_ds_in', target: 'b_bus1' },
      { id: 'be4', source: 'b_bus1', target: 'b_br_coupler' },
      { id: 'be5', source: 'b_br_coupler', target: 'b_bus2' },
      { id: 'be6', source: 'b_bus1', target: 'b_ds_out' },
      { id: 'be7', source: 'b_ds_out', target: 'b_br_out' },
      { id: 'be8', source: 'b_br_out', target: 'b_boundary_bc' },
      { id: 'be9', source: 'b_bus2', target: 'b_ds_xf' },
      { id: 'be10', source: 'b_ds_xf', target: 'b_br_xf' },
      { id: 'be11', source: 'b_br_xf', target: 'b_xf' },
      { id: 'be12', source: 'b_xf', target: 'b_bus_lv' },
      { id: 'be13', source: 'b_bus_lv', target: 'b_load' },
    ],
  }
  return {
    id: 'stB',
    name: 'B变电站',
    voltageSummary: '220/110kV',
    busScheme: 'double',
    graph,
    ports: [
      {
        id: 'port_b_ba',
        stationId: 'stB',
        deviceId: 'b_boundary_ba',
        name: 'B进线边界(自A)',
      },
      {
        id: 'port_b_bc',
        stationId: 'stB',
        deviceId: 'b_boundary_bc',
        name: 'B出线边界(至C)',
      },
    ],
    overviewPosition: { x: 380, y: 160 },
  }
}

function stationC(): StationDoc {
  const graph: TopologyGraph = {
    nodes: [
      {
        id: 'c_boundary_cb',
        type: 'disconnector',
        name: 'C进线边界(自B)',
        stationId: 'stC',
        voltage: '220kV',
        closed: true,
        isBoundary: true,
        x: 160,
        y: 40,
      },
      {
        id: 'c_br_in',
        type: 'breaker',
        name: 'C进线开关',
        stationId: 'stC',
        voltage: '220kV',
        closed: true,
        x: 160,
        y: 90,
      },
      {
        id: 'c_bus',
        type: 'bus',
        name: 'C桥接线母线',
        stationId: 'stC',
        voltage: '220kV',
        x: 80,
        y: 160,
        width: 200,
        height: 10,
      },
      {
        id: 'c_br_bridge',
        type: 'breaker',
        name: '桥开关',
        stationId: 'stC',
        voltage: '220kV',
        closed: true,
        x: 100,
        y: 200,
      },
      {
        id: 'c_xf',
        type: 'transformer',
        name: 'C主变',
        stationId: 'stC',
        voltage: '220/110',
        x: 200,
        y: 200,
      },
      {
        id: 'c_br_load',
        type: 'breaker',
        name: 'C负荷开关',
        stationId: 'stC',
        voltage: '220kV',
        closed: true,
        x: 160,
        y: 290,
      },
      {
        id: 'c_load',
        type: 'load',
        name: 'C站负荷',
        stationId: 'stC',
        voltage: '220kV',
        x: 157,
        y: 350,
      },
    ],
    edges: [
      { id: 'ce1', source: 'c_boundary_cb', target: 'c_br_in' },
      { id: 'ce2', source: 'c_br_in', target: 'c_bus' },
      { id: 'ce3', source: 'c_bus', target: 'c_br_bridge' },
      { id: 'ce4', source: 'c_bus', target: 'c_xf' },
      { id: 'ce5', source: 'c_br_bridge', target: 'c_br_load' },
      { id: 'ce6', source: 'c_xf', target: 'c_br_load' },
      { id: 'ce7', source: 'c_br_load', target: 'c_load' },
    ],
  }
  return {
    id: 'stC',
    name: 'C变电站',
    voltageSummary: '220kV',
    busScheme: 'bridge',
    graph,
    ports: [
      {
        id: 'port_c_cb',
        stationId: 'stC',
        deviceId: 'c_boundary_cb',
        name: 'C进线边界(自B)',
      },
    ],
    overviewPosition: { x: 700, y: 160 },
  }
}

export function createSampleProject(): GridProject {
  const stA = stationA()
  const stB = stationB()
  const stC = stationC()
  return {
    version: 1,
    overview: {
      tieLines: [
        {
          id: 'tie_ab',
          name: 'A-B线 220kV',
          voltage: '220kV',
          fromStationId: 'stA',
          toStationId: 'stB',
          fromPortId: 'port_a_ab',
          toPortId: 'port_b_ba',
        },
        {
          id: 'tie_bc',
          name: 'B-C线 220kV',
          voltage: '220kV',
          fromStationId: 'stB',
          toStationId: 'stC',
          fromPortId: 'port_b_bc',
          toPortId: 'port_c_cb',
        },
      ],
    },
    stations: {
      stA,
      stB,
      stC,
    },
  }
}
