import type { TopologyGraph } from './types'

/**
 * D5000 风格 3 站主网单线简图（简化间隔接线）
 *
 * A站(电源) ——联络线—— B站(中间/主变) ——联络线—— C站(负荷)
 *
 * 间隔顺序贴近调度图：母线 → 刀闸 → 断路器 → 刀闸 → 出线/设备
 */
export const sampleThreeStationGraph: TopologyGraph = {
  nodes: [
    // ========== A 站 ==========
    {
      id: 'stA',
      type: 'station',
      name: 'A变电站',
      voltage: '220kV',
      x: 40,
      y: 30,
      width: 260,
      height: 420,
    },
    {
      id: 'busA',
      type: 'bus',
      name: 'A-220kVⅠ母',
      stationId: 'stA',
      voltage: '220kV',
      x: 70,
      y: 120,
      width: 200,
      height: 10,
    },
    // 电源间隔
    {
      id: 'dsA_src',
      type: 'disconnector',
      name: 'A电源刀闸',
      stationId: 'stA',
      voltage: '220kV',
      closed: true,
      x: 110,
      y: 160,
    },
    {
      id: 'brA_src',
      type: 'breaker',
      name: 'A电源开关',
      stationId: 'stA',
      voltage: '220kV',
      closed: true,
      x: 110,
      y: 210,
    },
    {
      id: 'power',
      type: 'powerSource',
      name: '系统电源',
      isPowerSource: true,
      stationId: 'stA',
      voltage: '220kV',
      x: 99,
      y: 270,
    },
    // A 出线间隔
    {
      id: 'dsA_out1',
      type: 'disconnector',
      name: 'A出线刀闸1',
      stationId: 'stA',
      voltage: '220kV',
      closed: true,
      x: 200,
      y: 160,
    },
    {
      id: 'brA_out',
      type: 'breaker',
      name: 'A出线开关',
      stationId: 'stA',
      voltage: '220kV',
      closed: true,
      x: 200,
      y: 210,
    },
    {
      id: 'dsA_out2',
      type: 'disconnector',
      name: 'A出线刀闸2',
      stationId: 'stA',
      voltage: '220kV',
      closed: true,
      x: 200,
      y: 270,
    },

    // ========== B 站 ==========
    {
      id: 'stB',
      type: 'station',
      name: 'B变电站',
      voltage: '220/110kV',
      x: 380,
      y: 30,
      width: 340,
      height: 520,
    },
    // B 进线间隔
    {
      id: 'dsB_in2',
      type: 'disconnector',
      name: 'B进线刀闸2',
      stationId: 'stB',
      voltage: '220kV',
      closed: true,
      x: 430,
      y: 70,
    },
    {
      id: 'brB_in',
      type: 'breaker',
      name: 'B进线开关',
      stationId: 'stB',
      voltage: '220kV',
      closed: true,
      x: 430,
      y: 120,
    },
    {
      id: 'dsB_in1',
      type: 'disconnector',
      name: 'B进线刀闸1',
      stationId: 'stB',
      voltage: '220kV',
      closed: true,
      x: 430,
      y: 170,
    },
    {
      id: 'busB',
      type: 'bus',
      name: 'B-220kVⅠ母',
      stationId: 'stB',
      voltage: '220kV',
      x: 410,
      y: 220,
      width: 280,
      height: 10,
    },
    // B 出线间隔
    {
      id: 'dsB_out1',
      type: 'disconnector',
      name: 'B出线刀闸1',
      stationId: 'stB',
      voltage: '220kV',
      closed: true,
      x: 620,
      y: 170,
    },
    {
      id: 'brB_out',
      type: 'breaker',
      name: 'B出线开关',
      stationId: 'stB',
      voltage: '220kV',
      closed: true,
      x: 620,
      y: 120,
    },
    {
      id: 'dsB_out2',
      type: 'disconnector',
      name: 'B出线刀闸2',
      stationId: 'stB',
      voltage: '220kV',
      closed: true,
      x: 620,
      y: 70,
    },
    // 主变间隔
    {
      id: 'dsB_xf',
      type: 'disconnector',
      name: '主变高压刀闸',
      stationId: 'stB',
      voltage: '220kV',
      closed: true,
      x: 520,
      y: 260,
    },
    {
      id: 'brB_xf',
      type: 'breaker',
      name: '主变高压开关',
      stationId: 'stB',
      voltage: '220kV',
      closed: true,
      x: 520,
      y: 310,
    },
    {
      id: 'xfB',
      type: 'transformer',
      name: '#1主变',
      stationId: 'stB',
      voltage: '220/110',
      x: 509,
      y: 365,
    },
    {
      id: 'busB_lv',
      type: 'bus',
      name: 'B-110kVⅠ母',
      stationId: 'stB',
      voltage: '110kV',
      x: 450,
      y: 450,
      width: 200,
      height: 10,
    },
    {
      id: 'brB_load',
      type: 'breaker',
      name: 'B负荷开关',
      stationId: 'stB',
      voltage: '110kV',
      closed: true,
      x: 510,
      y: 480,
    },
    {
      id: 'loadB',
      type: 'load',
      name: 'B站负荷',
      stationId: 'stB',
      voltage: '110kV',
      x: 507,
      y: 530,
    },

    // ========== C 站 ==========
    {
      id: 'stC',
      type: 'station',
      name: 'C变电站',
      voltage: '220kV',
      x: 800,
      y: 30,
      width: 260,
      height: 360,
    },
    {
      id: 'dsC_in2',
      type: 'disconnector',
      name: 'C进线刀闸2',
      stationId: 'stC',
      voltage: '220kV',
      closed: true,
      x: 900,
      y: 70,
    },
    {
      id: 'brC_in',
      type: 'breaker',
      name: 'C进线开关',
      stationId: 'stC',
      voltage: '220kV',
      closed: true,
      x: 900,
      y: 120,
    },
    {
      id: 'dsC_in1',
      type: 'disconnector',
      name: 'C进线刀闸1',
      stationId: 'stC',
      voltage: '220kV',
      closed: true,
      x: 900,
      y: 170,
    },
    {
      id: 'busC',
      type: 'bus',
      name: 'C-220kVⅠ母',
      stationId: 'stC',
      voltage: '220kV',
      x: 830,
      y: 220,
      width: 200,
      height: 10,
    },
    {
      id: 'dsC_load',
      type: 'disconnector',
      name: 'C负荷刀闸',
      stationId: 'stC',
      voltage: '220kV',
      closed: true,
      x: 900,
      y: 260,
    },
    {
      id: 'brC_load',
      type: 'breaker',
      name: 'C负荷开关',
      stationId: 'stC',
      voltage: '220kV',
      closed: true,
      x: 900,
      y: 310,
    },
    {
      id: 'loadC',
      type: 'load',
      name: 'C站负荷',
      stationId: 'stC',
      voltage: '220kV',
      x: 897,
      y: 365,
    },
  ],
  edges: [
    // A 电源间隔
    { id: 'e_busA_dsSrc', source: 'busA', target: 'dsA_src' },
    { id: 'e_dsSrc_brSrc', source: 'dsA_src', target: 'brA_src' },
    { id: 'e_brSrc_power', source: 'brA_src', target: 'power' },
    // A 出线间隔
    { id: 'e_busA_dsOut1', source: 'busA', target: 'dsA_out1' },
    { id: 'e_dsOut1_brA', source: 'dsA_out1', target: 'brA_out' },
    { id: 'e_brA_dsOut2', source: 'brA_out', target: 'dsA_out2' },
    // A-B 联络线
    { id: 'e_line_AB', source: 'dsA_out2', target: 'dsB_in2', name: 'A-B线 220kV' },
    // B 进线
    { id: 'e_dsBin2_brBin', source: 'dsB_in2', target: 'brB_in' },
    { id: 'e_brBin_dsBin1', source: 'brB_in', target: 'dsB_in1' },
    { id: 'e_dsBin1_busB', source: 'dsB_in1', target: 'busB' },
    // B 出线
    { id: 'e_busB_dsBout1', source: 'busB', target: 'dsB_out1' },
    { id: 'e_dsBout1_brBout', source: 'dsB_out1', target: 'brB_out' },
    { id: 'e_brBout_dsBout2', source: 'brB_out', target: 'dsB_out2' },
    // B-C 联络线
    { id: 'e_line_BC', source: 'dsB_out2', target: 'dsC_in2', name: 'B-C线 220kV' },
    // B 主变
    { id: 'e_busB_dsXf', source: 'busB', target: 'dsB_xf' },
    { id: 'e_dsXf_brXf', source: 'dsB_xf', target: 'brB_xf' },
    { id: 'e_brXf_xf', source: 'brB_xf', target: 'xfB' },
    { id: 'e_xf_lv', source: 'xfB', target: 'busB_lv' },
    { id: 'e_lv_brLoad', source: 'busB_lv', target: 'brB_load' },
    { id: 'e_brLoad_loadB', source: 'brB_load', target: 'loadB' },
    // C 进线与负荷
    { id: 'e_dsCin2_brC', source: 'dsC_in2', target: 'brC_in' },
    { id: 'e_brC_dsCin1', source: 'brC_in', target: 'dsC_in1' },
    { id: 'e_dsCin1_busC', source: 'dsC_in1', target: 'busC' },
    { id: 'e_busC_dsLoad', source: 'busC', target: 'dsC_load' },
    { id: 'e_dsLoad_brLoad', source: 'dsC_load', target: 'brC_load' },
    { id: 'e_brLoad_loadC', source: 'brC_load', target: 'loadC' },
  ],
}
