import type { TopologyGraph } from './types'

/**
 * 3 站简化主网样例：
 * 电源站(A) -- 联络线 -- 中间站(B) -- 联络线 -- 负荷站(C)
 * 各站含母线、进出线断路器；B 站有变压器与负荷。
 */
export const sampleThreeStationGraph: TopologyGraph = {
  nodes: [
    // Station A - 电源侧
    {
      id: 'stA',
      type: 'station',
      name: 'A站(电源)',
      x: 40,
      y: 40,
      width: 220,
      height: 280,
    },
    {
      id: 'power',
      type: 'powerSource',
      name: '系统电源',
      isPowerSource: true,
      stationId: 'stA',
      voltage: '220kV',
      x: 100,
      y: 80,
    },
    {
      id: 'busA',
      type: 'bus',
      name: 'A站母线',
      stationId: 'stA',
      voltage: '220kV',
      x: 80,
      y: 160,
      width: 140,
      height: 16,
    },
    {
      id: 'brA_out',
      type: 'breaker',
      name: 'A出线开关',
      stationId: 'stA',
      closed: true,
      x: 120,
      y: 220,
    },

    // Station B - 中间站
    {
      id: 'stB',
      type: 'station',
      name: 'B站(中间)',
      x: 340,
      y: 40,
      width: 260,
      height: 360,
    },
    {
      id: 'brB_in',
      type: 'breaker',
      name: 'B进线开关',
      stationId: 'stB',
      closed: true,
      x: 380,
      y: 100,
    },
    {
      id: 'busB',
      type: 'bus',
      name: 'B站220母线',
      stationId: 'stB',
      voltage: '220kV',
      x: 360,
      y: 170,
      width: 160,
      height: 16,
    },
    {
      id: 'brB_xf',
      type: 'breaker',
      name: '主变高压侧',
      stationId: 'stB',
      closed: true,
      x: 420,
      y: 220,
    },
    {
      id: 'xfB',
      type: 'transformer',
      name: 'B主变',
      stationId: 'stB',
      voltage: '220/110',
      x: 410,
      y: 280,
    },
    {
      id: 'busB_lv',
      type: 'bus',
      name: 'B站110母线',
      stationId: 'stB',
      voltage: '110kV',
      x: 360,
      y: 340,
      width: 160,
      height: 16,
    },
    {
      id: 'loadB',
      type: 'load',
      name: 'B站负荷',
      stationId: 'stB',
      x: 500,
      y: 330,
    },
    {
      id: 'brB_out',
      type: 'breaker',
      name: 'B出线开关',
      stationId: 'stB',
      closed: true,
      x: 520,
      y: 100,
    },
    {
      id: 'dsB',
      type: 'disconnector',
      name: 'B刀闸',
      stationId: 'stB',
      closed: true,
      x: 460,
      y: 100,
    },

    // Station C - 负荷侧
    {
      id: 'stC',
      type: 'station',
      name: 'C站(负荷)',
      x: 680,
      y: 40,
      width: 220,
      height: 280,
    },
    {
      id: 'brC_in',
      type: 'breaker',
      name: 'C进线开关',
      stationId: 'stC',
      closed: true,
      x: 740,
      y: 100,
    },
    {
      id: 'busC',
      type: 'bus',
      name: 'C站母线',
      stationId: 'stC',
      voltage: '220kV',
      x: 720,
      y: 170,
      width: 140,
      height: 16,
    },
    {
      id: 'loadC',
      type: 'load',
      name: 'C站负荷',
      stationId: 'stC',
      x: 760,
      y: 240,
    },
  ],
  edges: [
    { id: 'e_p_busA', source: 'power', target: 'busA' },
    { id: 'e_busA_brA', source: 'busA', target: 'brA_out' },
    { id: 'e_line_AB', source: 'brA_out', target: 'brB_in', name: 'A-B联络线' },
    { id: 'e_brB_busB', source: 'brB_in', target: 'busB' },
    { id: 'e_busB_ds', source: 'busB', target: 'dsB' },
    { id: 'e_ds_brBout', source: 'dsB', target: 'brB_out' },
    { id: 'e_busB_brXf', source: 'busB', target: 'brB_xf' },
    { id: 'e_brXf_xf', source: 'brB_xf', target: 'xfB' },
    { id: 'e_xf_lv', source: 'xfB', target: 'busB_lv' },
    { id: 'e_lv_loadB', source: 'busB_lv', target: 'loadB' },
    { id: 'e_line_BC', source: 'brB_out', target: 'brC_in', name: 'B-C联络线' },
    { id: 'e_brC_busC', source: 'brC_in', target: 'busC' },
    { id: 'e_busC_loadC', source: 'busC', target: 'loadC' },
  ],
}
